In [1]:
import pandas as pd
import os

In [2]:
#CSV file location
csv_path = "Arrest_Data_from_2010_to_Present.csv"

In [3]:
#Reading the CSV file
arrest_data = pd.read_csv(csv_path, engine="python")
arrest_data

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
0,191811472,05/03/2019,1700.0,18,Southeast,1802,23,F,B,NaN,NaN,M,653.22 PC,NaN,91ST,FIGUEROA,"(33.9543, -118.2827)"
1,5614161,04/29/2019,1040.0,8,West LA,842,41,M,H,3.0,Robbery,F,211PC,ROBBERY,11600 WILSHIRE BL,NaN,"(34.0508, -118.4592)"
2,5806609,11/23/2019,1830.0,4,Hollenbeck,457,23,F,H,3.0,Robbery,F,211PC,ROBBERY,FICKETT,CINCINNATI,"(34.0477, -118.2047)"
3,5615197,04/30/2019,615.0,6,Hollywood,663,27,M,O,5.0,Burglary,F,459PC,BURGLARY,LA BREA,LEXINGTON,"(34.0907, -118.3384)"
4,5615701,04/30/2019,1100.0,9,Van Nuys,901,2,F,H,NaN,NaN,D,300(B)WIC,NaN,RAYMER,SEPULVEDA BL,"(34.2149, -118.4674)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1331487,5612927,04/27/2019,2355.0,21,Topanga,2125,22,M,H,22.0,Driving Under Influence,M,23152(G)VC,DUI OF ALCOHOL & DRUG,STRATHERN,CANOGA,"(34.2156, -118.5975)"
1331488,5612964,04/27/2019,1829.0,1,Central,161,30,M,W,8.0,Other Assaults,F,69PC,OBSTRUCT/RESIST EXECUTIVE OFFICER,HARBOR FY,4TH ST,"(34.0483, -118.2631)"
1331489,5612940,04/27/2019,2315.0,17,Devonshire,1797,42,M,H,4.0,Aggravated Assault,F,273.5(A)PC,CORPORAL INJURY ON SPOUSE/COHABITANT/ETC,8500 RUBIO AV,NaN,"(34.2248, -118.4967)"
1331490,5612654,04/27/2019,1555.0,18,Southeast,1832,38,F,H,4.0,Aggravated Assault,F,273.5(A)PC,CORPORAL INJURY ON SPOUSE/COHABITANT/ETC,100 E 104TH ST,NaN,"(33.942, -118.2739)"
1331491,5612691,04/27/2019,1545.0,12,77th Street,1203,32,F,B,4.0,Aggravated Assault,F,245(A)(1)PC,"ADW, NOT FIREARM, W/GBI",1600 W 52ND ST,NaN,"(33.9994, -118.3108)"

In [4]:
#Determining number of of arrests for each charge type/description
arrest_data["Charge Description"].value_counts()

DRUNK DRIVING ALCOHOL/DRUGS                 99056
DRINKING IN PUBLIC                          93978
CORPORAL INJURY ON SPOUSE/COHABITANT/ETC    47644
POSSESSION CONTROLLED SUBSTANCE             45739
FTA AFTER WRITTEN PROMISE                   31681
                                            ...
DRIVE AGAINST TRAFFIC/ONE-WAY STREET            1
FALSE STATEMENT/IMMIGRATION MATTER              1
FRAUDULENT CONVEYANCES OF PROPERTY              1
PERMIT ANIMAL TO GO WITHOUT CARE                1
ACT AS VEHICLE SALESMAN W/O LICENSE             1
Name: Charge Description, Length: 2371, dtype: int64

In [5]:
#Creating a new CSV file that show us all of the unique values in "charge description" column
pd.DataFrame({"descriptions":arrest_data["Charge Description"].unique()}).to_csv("drunkdesc.csv")

In [14]:
#Pulling data only with key words applicable to intoxication (e.g. drunk, drinking, alcohol, etc.)
drunk_descriptions = [desc for desc in arrest_data["Charge Description"].unique() if "DRUNK" in str(desc) or "ALCOHOL" in str(desc) or "DRINKING" in str(desc) or "DUI" in str(desc) or "INTOXICATION" in str(desc)]
drunk_descriptions

['OPEN ALCOHOLIC BEV IN PUBLIC PARK/PLACE',
 'DRUNK DRIVING ALCOHOL/DRUGS',
 'DRINKING IN PUBLIC',
 'DRINKING ALCOHOL*******',
 'SALE/ETC OF ALCOHOLIC BEVERAGE TO MINOR',
 'DRINKING IN PUBLIC***',
 'MINOR POSSESS ALCOHOL',
 'VEH MANSLAUGHTR/OPER VESSEL DUI & DUR FEL',
 'VEH MANSLAUGHTER DUI W/GROSS NEGLIGENCE',
 'DUI ALCOHOL CAUSING INJURY',
 'DRUNK DRIVING .10 OR ABOVE',
 'BRING/SEND NARC/CONT SUBS/ALCOHOL TO JAIL',
 'DISORD CONDUCT:UI/DRUG, ALCOHOL',
 'DUI W/PRIOR SPEC CONVICTIONS',
 'DUI OF ANY DRUG',
 'DUI .08 ALCOHOL CAUSING INJURY',
 'DUI ALCOHOL/DRUGS ON BICYCLE',
 'DRINKING ALCOHOL',
 'DUI ALCOHOL/DRUG W/PRIORS',
 'DUI OF ALCOHOL & DRUG',
 'POSS DRUGS/ALCOHOLIC BEV:PRISON/JAIL',
 'MINOR DRIVE W/BLOOD ALCOHOL OF 0.05%+',
 'SELL/LET MINOR CONSUME ALCOHOL',
 'ALCOHOLIC BEV LICENSEE POSS UNAUTH LIQ',
 'MINOR IN POSSESSION OF ALCOHOLIC BEVERAGE',
 'DUI OF A DRUG CAUSING INJURY',
 'DRUNK DRIVING ADDICT DRIVE VEHICLE',
 'POSS NARC/DRUG/ALCOHOL/DRUG PARAPH:JAIL',
 'ALCOHOLIC BEV SALES TO INTOXICATED PERSNS',
 'DUI OF COMB DRUG & ALCOHOL INFLUENCE',
 'FELONY FOR FOURTH DUI',
 'PERMIT BEGGING/SOLICITING OF ALCOHOL',
 'DUI OF ALCOHOL & DRUG CAUSING INJURY',
 'DUI ALCOHOL/0.08 W/PRS',
 'CONSUME/PURCHASE ALCOHOLIC BEV BY MINOR',
 'DRINK ALCOHOLIC BEVERAGE IN VEH ON HWY',
 'DRIVE SUS/REV DUI W/IN 5 YRS PRIOR OFFNS',
 'TRANSPORT ALCOHOLIC BEVERAGE BY MINOR',
 'SELL/PURCHASE ALCOHOL AFTER HOURS',
 'MINOR IN POSS OF ALCOHOL BEVERAGE IN VEH',
 'DRUNK, ALCOHOL',
 'ALCOHOLIC BEV LIC PERMIT ALCHL CONSMPTN',
 'OFFER OF SUBSTITUTE ALCOHOLIC BEV BRAND',
 'POSSESS ANY ALCOHOLIC BEV LIST IN BP2535',
 'NO DRINKING SIGN REQ OFF-SALE PREM',
 'MFG/SELL/ETC ALCOHOL CONTAIN POISN SUBS',
 'MINOR ATT PURCHASE ALCOHOLIC BEVERAGE',
 'EMPLOY MINOR WHERE ALCOHOL SOLD',
 'MINOR EMPLOYED WHERE ALCOHOL IS SOLD',
 '< AGE 21 DRIVING VEH W/BLOOD-ALCOHOL .01+',
 'POSS OF OPEN CONTAINER OF ALCOHOL IN PARK',
 'FURNISH ALCOHOLIC BEVERAGE TO A MINOR',
 'DUI WITH PRIOR CONVITIONS',
 'DUI BOAT OR WATERCRAFT',
 'DRUNK DRIVING',
 'SODOMY ANESTHESIA/CNTL SUBS/INTOXICATION',
 'DUI W/PRIOR SEPC CONVICTIONS',
 'DUI DRUGS',
 'DUI/BOAT OR WATERCRAFT',
 'VEH MANSLAUGHTER DUI W/O GROSS NEGLIGENCE',
 'DUI W/PRIOR SPECIFIC CONVICTIONS',
 'DUI WITH PRIOR CONVICTIONS',
 'ATTEMPT DRUNK DRIVING',
 'DRIVE RESTRICT DUI W/IN 5 YEARS PRIOR OFF']

In [15]:
#Failed attempt at a code
#arrest_data['Charge Description'].value_counts().index

In [16]:
#Just determining how many line items there are in the data set
arrest_data["Report ID"].count()

1331492

In [9]:
#Creating a data frame with only drunk related information
drunk_data = arrest_data[arrest_data['Charge Description'].isin(drunk_descriptions)]
#drunk_data["Charge Description"].unique()
drunk_data.head()

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
10,190325212,11/23/2019,1315.0,3,Southwest,328,21,F,W,17.0,Liquor Laws,I,25620BP,OPEN ALCOHOLIC BEV IN PUBLIC PARK/PLACE,28TH ST,E UNIVERSITY,"(34.0278, -118.281)"
13,5809994,11/27/2019,2100.0,18,Southeast,1801,20,M,H,22.0,Driving Under Influence,M,23152(A)VC,DRUNK DRIVING ALCOHOL/DRUGS,FIGUEROA,MANCHESTER,"(33.9601, -118.2827)"
20,190818921,11/27/2019,1645.0,8,West LA,893,42,M,W,18.0,Drunkeness,M,41.27CLAMC,DRINKING IN PUBLIC,SEPULVEDA BL,PEARL,"(34.0344, -118.4336)"
26,5672540,11/24/2019,356.0,15,N Hollywood,1547,30,M,H,22.0,Driving Under Influence,M,23152(A)VC,DRUNK DRIVING ALCOHOL/DRUGS,BURBANK,HOLLYWOOD FY,"(34.1673, -118.3816)"
29,5806232,11/23/2019,149.0,2,Rampart,239,25,M,H,22.0,Driving Under Influence,M,23152(A)VC,DRUNK DRIVING ALCOHOL/DRUGS,WESTERN AV,101 SOUTHBOUND,"(34.0609, -118.2535)"

In [10]:
# drunk_data['Arrest Date'] = pd.date_range('2016-1-1', '2020-1-1', freq='D')
# mask = (drunk_data['Arrest Date'] > '2016-1-1') & (drunk_data['Arrest Date'] <= '2020-1-1'

In [11]:
drunk_data["Arrest Date"] = pd.to_datetime(drunk_data["Arrest Date"])
drunk_data.head()

C:\Users\ayoat001\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
10,190325212,2019-11-23,1315.0,3,Southwest,328,21,F,W,17.0,Liquor Laws,I,25620BP,OPEN ALCOHOLIC BEV IN PUBLIC PARK/PLACE,28TH ST,E UNIVERSITY,"(34.0278, -118.281)"
13,5809994,2019-11-27,2100.0,18,Southeast,1801,20,M,H,22.0,Driving Under Influence,M,23152(A)VC,DRUNK DRIVING ALCOHOL/DRUGS,FIGUEROA,MANCHESTER,"(33.9601, -118.2827)"
20,190818921,2019-11-27,1645.0,8,West LA,893,42,M,W,18.0,Drunkeness,M,41.27CLAMC,DRINKING IN PUBLIC,SEPULVEDA BL,PEARL,"(34.0344, -118.4336)"
26,5672540,2019-11-24,356.0,15,N Hollywood,1547,30,M,H,22.0,Driving Under Influence,M,23152(A)VC,DRUNK DRIVING ALCOHOL/DRUGS,BURBANK,HOLLYWOOD FY,"(34.1673, -118.3816)"
29,5806232,2019-11-23,149.0,2,Rampart,239,25,M,H,22.0,Driving Under Influence,M,23152(A)VC,DRUNK DRIVING ALCOHOL/DRUGS,WESTERN AV,101 SOUTHBOUND,"(34.0609, -118.2535)"

In [12]:
from datetime import date
drunk_data.loc[drunk_data['Arrest Date'] > date(2016, 1, 1)]
drunk_data

C:\Users\ayoat001\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Comparing Series of datetimes with 'datetime.date'.  Currently, the
'datetime.date' is coerced to a datetime. In the future pandas will
not coerce, and a TypeError will be raised. To retain the current
behavior, convert the 'datetime.date' to a datetime with
'pd.Timestamp'.

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
10,190325212,2019-11-23,1315.0,3,Southwest,328,21,F,W,17.0,Liquor Laws,I,25620BP,OPEN ALCOHOLIC BEV IN PUBLIC PARK/PLACE,28TH ST,E UNIVERSITY,"(34.0278, -118.281)"
13,5809994,2019-11-27,2100.0,18,Southeast,1801,20,M,H,22.0,Driving Under Influence,M,23152(A)VC,DRUNK DRIVING ALCOHOL/DRUGS,FIGUEROA,MANCHESTER,"(33.9601, -118.2827)"
20,190818921,2019-11-27,1645.0,8,West LA,893,42,M,W,18.0,Drunkeness,M,41.27CLAMC,DRINKING IN PUBLIC,SEPULVEDA BL,PEARL,"(34.0344, -118.4336)"
26,5672540,2019-11-24,356.0,15,N Hollywood,1547,30,M,H,22.0,Driving Under Influence,M,23152(A)VC,DRUNK DRIVING ALCOHOL/DRUGS,BURBANK,HOLLYWOOD FY,"(34.1673, -118.3816)"
29,5806232,2019-11-23,149.0,2,Rampart,239,25,M,H,22.0,Driving Under Influence,M,23152(A)VC,DRUNK DRIVING ALCOHOL/DRUGS,WESTERN AV,101 SOUTHBOUND,"(34.0609, -118.2535)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1331434,5606768,2019-04-21,245.0,7,Wilshire,759,28,M,O,22.0,Driving Under Influence,F,23153(F)VC,DUI OF A DRUG CAUSING INJURY,PICO BL,5TH AV,"(34.0475, -118.323)"
1331446,5606554,2019-04-20,2100.0,15,N Hollywood,1521,27,M,H,22.0,Driving Under Influence,M,23152(F)VC,DUI OF ANY DRUG,SHERMAN WY,ETHEL AV,"(34.2012, -118.4211)"
1331447,5610860,2019-04-25,1925.0,9,Van Nuys,935,48,M,H,22.0,Driving Under Influence,M,23152(A)VC,DRUNK DRIVING ALCOHOL/DRUGS,6200 SYLMAR AV,NaN,"(34.1827, -118.4465)"
1331462,9391083,2010-01-19,35.0,8,West LA,842,29,F,H,22.0,Driving Under Influence,M,23152(A)VC,DRUNK DRIVING ALCOHOL/DRUGS,WILSHIRE BL,GRANVILLE AV,"(34.048, -118.4626)"
1331487,5612927,2019-04-27,2355.0,21,Topanga,2125,22,M,H,22.0,Driving Under Influence,M,23152(G)VC,DUI OF ALCOHOL & DRUG,STRATHERN,CANOGA,"(34.2156, -118.5975)"

In [17]:
drunk_data.to_csv("Intoxication Data.csv", index=False, header=True)