In [2]:
import gmaps
import pandas as pd

# Google developer API key
from config import api_key

# Configure gmaps

gmaps.configure(api_key)
print(api_key)

AIzaSyDW91Gci6WJOxSJbjSnmEFuQkNzog_HMqM

In [3]:
# Create df
df_latlong = pd.read_csv('../harmonious_hummingbirds/Intoxication_Data.csv')
df_latlong.dropna()
df_latlong.head()

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
0,190325212,2019-11-23,1315.0,3,Southwest,328,21,F,W,17.0,Liquor Laws,I,25620BP,OPEN ALCOHOLIC BEV IN PUBLIC PARK/PLACE,28TH ST,E UNIVERSITY,"(34.0278, -118.281)"
1,5809994,2019-11-27,2100.0,18,Southeast,1801,20,M,H,22.0,Driving Under Influence,M,23152(A)VC,DRUNK DRIVING ALCOHOL/DRUGS,FIGUEROA,MANCHESTER,"(33.9601, -118.2827)"
2,190818921,2019-11-27,1645.0,8,West LA,893,42,M,W,18.0,Drunkeness,M,41.27CLAMC,DRINKING IN PUBLIC,SEPULVEDA BL,PEARL,"(34.0344, -118.4336)"
3,5672540,2019-11-24,356.0,15,N Hollywood,1547,30,M,H,22.0,Driving Under Influence,M,23152(A)VC,DRUNK DRIVING ALCOHOL/DRUGS,BURBANK,HOLLYWOOD FY,"(34.1673, -118.3816)"
4,5806232,2019-11-23,149.0,2,Rampart,239,25,M,H,22.0,Driving Under Influence,M,23152(A)VC,DRUNK DRIVING ALCOHOL/DRUGS,WESTERN AV,101 SOUTHBOUND,"(34.0609, -118.2535)"

In [4]:
df_latlong = df_latlong.drop(['Time','Area ID','Charge','Area ID','Area Name','Descent Code','Charge Group Code','Reporting District'], axis=1)

In [22]:
df_latlong.nunique()

Report ID                   280105
Arrest Date                   3684
Age                             84
Sex Code                         2
Charge Group Description         8
Arrest Type Code                 3
Charge Description              63
Address                      23856
Cross Street                 10836
Location                     27648
dtype: int64

In [8]:
df_latlong = df_latlong.rename(columns={"Charge Group Description": "CGD"})

In [23]:
df_latlong['Charge Description'].unique()

array(['OPEN ALCOHOLIC BEV IN PUBLIC PARK/PLACE',
       'DRUNK DRIVING ALCOHOL/DRUGS', 'DRINKING IN PUBLIC',
       'DRINKING ALCOHOL*******',
       'SALE/ETC OF ALCOHOLIC BEVERAGE TO MINOR', 'DRINKING IN PUBLIC***',
       'MINOR POSSESS ALCOHOL',
       'VEH MANSLAUGHTR/OPER VESSEL DUI & DUR FEL',
       'VEH MANSLAUGHTER DUI W/GROSS NEGLIGENCE',
       'DUI ALCOHOL CAUSING INJURY', 'DRUNK DRIVING .10 OR ABOVE',
       'BRING/SEND NARC/CONT SUBS/ALCOHOL TO JAIL',
       'DISORD CONDUCT:UI/DRUG, ALCOHOL', 'DUI W/PRIOR SPEC CONVICTIONS',
       'DUI OF ANY DRUG', 'DUI .08 ALCOHOL CAUSING INJURY',
       'DUI ALCOHOL/DRUGS ON BICYCLE', 'DRINKING ALCOHOL',
       'DUI ALCOHOL/DRUG W/PRIORS', 'DUI OF ALCOHOL & DRUG',
       'POSS DRUGS/ALCOHOLIC BEV:PRISON/JAIL',
       'MINOR DRIVE W/BLOOD ALCOHOL OF 0.05%+',
       'SELL/LET MINOR CONSUME ALCOHOL',
       'ALCOHOLIC BEV LICENSEE POSS UNAUTH LIQ',
       'MINOR IN POSSESSION OF ALCOHOLIC BEVERAGE',
       'DUI OF A DRUG CAUSING INJURY',
       'DRUNK DRIVING ADDICT DRIVE VEHICLE',
       'POSS NARC/DRUG/ALCOHOL/DRUG PARAPH:JAIL',
       'ALCOHOLIC BEV SALES TO INTOXICATED PERSNS',
       'DUI OF COMB DRUG & ALCOHOL INFLUENCE', 'FELONY FOR FOURTH DUI',
       'PERMIT BEGGING/SOLICITING OF ALCOHOL',
       'DUI OF ALCOHOL & DRUG CAUSING INJURY', 'DUI ALCOHOL/0.08 W/PRS',
       'CONSUME/PURCHASE ALCOHOLIC BEV BY MINOR',
       'DRINK ALCOHOLIC BEVERAGE IN VEH ON HWY',
       'DRIVE SUS/REV DUI W/IN 5 YRS PRIOR OFFNS',
       'TRANSPORT ALCOHOLIC BEVERAGE BY MINOR',
       'SELL/PURCHASE ALCOHOL AFTER HOURS',
       'MINOR IN POSS OF ALCOHOL BEVERAGE IN VEH', 'DRUNK, ALCOHOL',
       'ALCOHOLIC BEV LIC PERMIT ALCHL CONSMPTN',
       'OFFER OF SUBSTITUTE ALCOHOLIC BEV BRAND',
       'POSSESS ANY ALCOHOLIC BEV LIST IN BP2535',
       'NO DRINKING SIGN REQ OFF-SALE PREM',
       'MFG/SELL/ETC ALCOHOL CONTAIN POISN SUBS',
       'MINOR ATT PURCHASE ALCOHOLIC BEVERAGE',
       'EMPLOY MINOR WHERE ALCOHOL SOLD',
       'MINOR EMPLOYED WHERE ALCOHOL IS SOLD',
       '< AGE 21 DRIVING VEH W/BLOOD-ALCOHOL .01+',
       'POSS OF OPEN CONTAINER OF ALCOHOL IN PARK',
       'FURNISH ALCOHOLIC BEVERAGE TO A MINOR',
       'DUI WITH PRIOR CONVITIONS', 'DUI BOAT OR WATERCRAFT',
       'DRUNK DRIVING', 'DUI W/PRIOR SEPC CONVICTIONS', 'DUI DRUGS',
       'DUI/BOAT OR WATERCRAFT',
       'VEH MANSLAUGHTER DUI W/O GROSS NEGLIGENCE',
       'DUI W/PRIOR SPECIFIC CONVICTIONS', 'DUI WITH PRIOR CONVICTIONS',
       'ATTEMPT DRUNK DRIVING',
       'DRIVE RESTRICT DUI W/IN 5 YEARS PRIOR OFF'], dtype=object)

In [24]:
df_latlong = df_latlong[df_latlong['CGD'] == 'Driving Under Influence']

In [25]:
df_coordinates = df_latlong.Location.str.extract(
    '^(?P<Location>.*)\s*\((?P<Latitude>[^,]*),\s*(?P<Longitude>\S*)\).*$',
    expand=True
)

In [26]:
	
# Merge two Dataframes on index of both the dataframes
df_merged = df_latlong.merge(df_coordinates, left_index=True, right_index=True)
df_merged

,Report ID,Arrest Date,Age,Sex Code,CGD,Arrest Type Code,Charge Description,Address,Cross Street,Location_x,Location_y,Latitude,Longitude
1,5809994,2019-11-27,20,M,Driving Under Influence,M,DRUNK DRIVING ALCOHOL/DRUGS,FIGUEROA,MANCHESTER,"(33.9601, -118.2827)",,33.9601,-118.2827
3,5672540,2019-11-24,30,M,Driving Under Influence,M,DRUNK DRIVING ALCOHOL/DRUGS,BURBANK,HOLLYWOOD FY,"(34.1673, -118.3816)",,34.1673,-118.3816
4,5806232,2019-11-23,25,M,Driving Under Influence,M,DRUNK DRIVING ALCOHOL/DRUGS,WESTERN AV,101 SOUTHBOUND,"(34.0609, -118.2535)",,34.0609,-118.2535
26,191008773,2019-04-20,28,M,Driving Under Influence,M,DRUNK DRIVING ALCOHOL/DRUGS,BURBANK BL,WOODLEY AV,"(34.1717, -118.4757)",,34.1717,-118.4757
39,5478957,2018-11-22,21,F,Driving Under Influence,F,DUI ALCOHOL CAUSING INJURY,SAN VICENTE,BARRINGTON,"(34.0536, -118.4655)",,34.0536,-118.4655
...,...,...,...,...,...,...,...,...,...,...,...,...,...
280100,5606768,2019-04-21,28,M,Driving Under Influence,F,DUI OF A DRUG CAUSING INJURY,PICO BL,5TH AV,"(34.0475, -118.323)",,34.0475,-118.323
280101,5606554,2019-04-20,27,M,Driving Under Influence,M,DUI OF ANY DRUG,SHERMAN WY,ETHEL AV,"(34.2012, -118.4211)",,34.2012,-118.4211
280102,5610860,2019-04-25,48,M,Driving Under Influence,M,DRUNK DRIVING ALCOHOL/DRUGS,6200 SYLMAR AV,NaN,"(34.1827, -118.4465)",,34.1827,-118.4465
280103,9391083,2010-01-19,29,F,Driving Under Influence,M,DRUNK DRIVING ALCOHOL/DRUGS,WILSHIRE BL,GRANVILLE AV,"(34.048, -118.4626)",,34.048,-118.4626
280104,5612927,2019-04-27,22,M,Driving Under Influence,M,DUI OF ALCOHOL & DRUG,STRATHERN,CANOGA,"(34.2156, -118.5975)",,34.2156,-118.5975

In [27]:
df_merged

crime_locations = df_merged[["Latitude", "Longitude"]]
crime_locations.dtypes

crime_locations["Latitude"] = crime_locations.Latitude.astype(float)
crime_locations["Longitude"] = crime_locations.Longitude.astype(float)

crime_locations

/Users/andrewwright/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/andrewwright/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

        Latitude  Longitude
1        33.9601  -118.2827
3        34.1673  -118.3816
4        34.0609  -118.2535
26       34.1717  -118.4757
39       34.0536  -118.4655
...          ...        ...
280100   34.0475  -118.3230
280101   34.2012  -118.4211
280102   34.1827  -118.4465
280103   34.0480  -118.4626
280104   34.2156  -118.5975

[122074 rows x 2 columns]

In [28]:
df_sampler = crime_locations.sample(10000)

In [37]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(df_sampler, dissipating=False, max_intensity=30, point_radius=0.006
)
 
# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [30]:
df_merged

,Report ID,Arrest Date,Age,Sex Code,CGD,Arrest Type Code,Charge Description,Address,Cross Street,Location_x,Location_y,Latitude,Longitude
1,5809994,2019-11-27,20,M,Driving Under Influence,M,DRUNK DRIVING ALCOHOL/DRUGS,FIGUEROA,MANCHESTER,"(33.9601, -118.2827)",,33.9601,-118.2827
3,5672540,2019-11-24,30,M,Driving Under Influence,M,DRUNK DRIVING ALCOHOL/DRUGS,BURBANK,HOLLYWOOD FY,"(34.1673, -118.3816)",,34.1673,-118.3816
4,5806232,2019-11-23,25,M,Driving Under Influence,M,DRUNK DRIVING ALCOHOL/DRUGS,WESTERN AV,101 SOUTHBOUND,"(34.0609, -118.2535)",,34.0609,-118.2535
26,191008773,2019-04-20,28,M,Driving Under Influence,M,DRUNK DRIVING ALCOHOL/DRUGS,BURBANK BL,WOODLEY AV,"(34.1717, -118.4757)",,34.1717,-118.4757
39,5478957,2018-11-22,21,F,Driving Under Influence,F,DUI ALCOHOL CAUSING INJURY,SAN VICENTE,BARRINGTON,"(34.0536, -118.4655)",,34.0536,-118.4655
...,...,...,...,...,...,...,...,...,...,...,...,...,...
280100,5606768,2019-04-21,28,M,Driving Under Influence,F,DUI OF A DRUG CAUSING INJURY,PICO BL,5TH AV,"(34.0475, -118.323)",,34.0475,-118.323
280101,5606554,2019-04-20,27,M,Driving Under Influence,M,DUI OF ANY DRUG,SHERMAN WY,ETHEL AV,"(34.2012, -118.4211)",,34.2012,-118.4211
280102,5610860,2019-04-25,48,M,Driving Under Influence,M,DRUNK DRIVING ALCOHOL/DRUGS,6200 SYLMAR AV,NaN,"(34.1827, -118.4465)",,34.1827,-118.4465
280103,9391083,2010-01-19,29,F,Driving Under Influence,M,DRUNK DRIVING ALCOHOL/DRUGS,WILSHIRE BL,GRANVILLE AV,"(34.048, -118.4626)",,34.048,-118.4626
280104,5612927,2019-04-27,22,M,Driving Under Influence,M,DUI OF ALCOHOL & DRUG,STRATHERN,CANOGA,"(34.2156, -118.5975)",,34.2156,-118.5975

In [103]:
# still need to remove some of the charge descriptions

In [107]:
df_merged.to_csv("df_crime.csv", index=False, header= True)